### ISSUE TITLE
sign up

### ISSUE THREAD

**Issue by aikenorganics** [aikenorganics/aikenorganics.com#29]
WHen you sign up you have to put your first, last name

**Comment by aikenorganics** [comment]
and phone number

**Comment by braddunbar** [comment]
Just deployed this to production. I made the phone number optional because I know some people don't like to give it out.

Thanks for being awesome. :smiley_cat:

**Comment by aikenorganics** [comment]
Do you think we should make ppl add there number incase i need to cal for a
pick up reminder?

Eat "Kale"fully
Alexandrea Kneece
alexandrea@aikenorganics.com
803.920.7153
www.aikenorganics.com
Like Aiken Organics on Facebook <http://www.facebook.com/aikenorganics>

**Comment by braddunbar** [comment]
Done and done. Phone number is now required!
