### ISSUE TITLE
Set Up Google Analytics

### ISSUE THREAD

**Issue by braddunbar** [aikenorganics/aikenorganics.com#3]
The account is created. Let's verify that it's working!

**Comment by aikenorganics** [comment]
What account?

**Comment by braddunbar** [comment]
It's the one you set up when we met. We won't be able to test it out until we're live at aikenorganics.com though.

**Comment by aikenorganics** [comment]
Can Stephen see what it looks like?  or can you do like a screen shot or
somethign so he can see?

**Comment by braddunbar** [comment]
Done and done!
