### ISSUE TITLE
Oversold View

### ISSUE THREAD

**Issue by braddunbar** [aikenorganics/aikenorganics.com#35]
If a product's supply has changed after it's already been ordered, we should know about it!

**Comment by braddunbar** [comment]
This is live in production and there are currently two oversold items. :grimacing: @aikenorganics What should we do about the ones that aren't you?

**Comment by aikenorganics** [comment]
What is it?

Alexandrea Kneece
803.920.7153
Aikenorganics.com

**Comment by braddunbar** [comment]
It's Beef Patties. Check them out [here](http://aikenorganics.com/admin/products/oversold).

**Comment by aikenorganics** [comment]
Yep. That's fine. I contacted mibek n getting extra. Three ppl instead of
2right?

Alexandrea Kneece
803.920.7153
Aikenorganics.com

**Comment by aikenorganics** [comment]
If something is overstock when you click that item can it tell you the
names of the ppl?

Eat "Kale"fully
Alexandrea Kneece
alexandrea@aikenorganics.com
803.920.7153
www.aikenorganics.com
Like Aiken Organics on Facebook <http://www.facebook.com/aikenorganics>

**Comment by braddunbar** [comment]
Yep, just added that. Check it out!
