### ISSUE TITLE
website adjustments

### ISSUE THREAD

**Issue by aikenorganics** [aikenorganics/aikenorganics.com#8]
the "menu bar" at the top of the screen, can the font be the same as "Making Local Easy"?

can there be a coming soon delivery on step 4

**Comment by braddunbar** [comment]
Updated in e6008c76316bef8c0ecc9b676457c75cf088859c. Whatcha think?

![screen shot 2015-02-28 at 6 56 57 pm](https://cloud.githubusercontent.com/assets/11674/6428782/b7cc7d46-bf7b-11e4-8b97-918846f52094.png)


![screen shot 2015-02-28 at 6 57 04 pm](https://cloud.githubusercontent.com/assets/11674/6428781/ad72f348-bf7b-11e4-8b2c-7635754be01c.png)

**Comment by aikenorganics** [comment]
I like the coming soon!

I meant to say same font  Aiken online farmers market
