### ISSUE TITLE
Heroku Account

### ISSUE THREAD

**Issue by braddunbar** [aikenorganics/aikenorganics.com#9]
@aikenorganics You're gonna need a heroku account with a credit card for hosting. Would you mind [setting one up here](https://www.heroku.com/)?

**Comment by aikenorganics** [comment]
Aikenorganics

password: Veggies2015

**Comment by aikenorganics** [comment]
alexandrea@aikenorganics.com

**Comment by braddunbar** [comment]
Done! Thanks Alley!
